### ISSUE TITLE
Integration appears to be broken

### ISSUE THREAD

**Issue by darkfrog26** [typpo/quickchart-java#10]
I've been using this library for a while and everything seemed to be working fine. All of a sudden I'm getting the following error when I try to generate a report:

```
Exception in thread "main" java.lang.RuntimeException: Received invalid status code 400 from API endpoint

Chart error: Error: Async/await not allowed
        at io.quickchart.QuickChart.executePost(QuickChart.java:258)
        at io.quickchart.QuickChart.toFile(QuickChart.java:321)
```

I presume that QuickChart changed functionality, but I haven't been able to find any details of what got changed.

**Comment by typpo** [comment]
Hi @darkfrog26, QuickChart hasn't deployed recently.  Do you have an example of a complete chart configuration that's causing this?

**Comment by darkfrog26** [comment]
I haven't had time to write a reproducible example, but it's still throwing the same error. Any idea what `Chart error: Error: Async/await not allowed` means in this context?
